myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('start/', views.start, name='start'),
    path('status/', views.status, name='status'),
    path('get_status/', views.get_status, name='get_status')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .tasks import bigtask
import redis
from django.conf import settings
from celery.result import AsyncResult


redis_instance = redis.StrictRedis(host=settings.REDIS_HOST,
                                   port=settings.REDIS_PORT)


# Create your views here.
def index(request):
    return render(request, 'myapp/index.html', {})


def start(request):
    result = bigtask.delay()
    task_id = result.id
    redis_instance.set('task_id', task_id)
    return render(request, 'myapp/start.html', {'task_id': task_id})


def status(request):
    return render(request, 'myapp/status.html', {})


def get_status(request):
    task_id = redis_instance.get('task_id')
    result = AsyncResult(task_id)
    if result.info is not None:
        return JsonResponse(result.info)
    else:
        return JsonResponse({})

myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>rishid</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
</head>
<body>
    <section class="hero">
        <div class="hero-body">
        <div class="container">
            <h4 class="title is-4">Hello world!</h4>
            <p class="subtitle">Django, Celery, Redis, Docker example</p>
        </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <a class="button is-medium" href="{% url 'myapp:start' %}">Start task</a>
        </div>
    </section>
</body>
</html>

myapp/templates/myapp/start.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>rishid</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
</head>
<body>
    <section class="hero">
        <div class="hero-body">
        <div class="container">
            <h4 class="title is-4">Hello world!</h4>
            <p class="subtitle">Django, Celery, Redis, Docker example</p>
        </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <p>Task with {{ task_id }} started.</p>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <a class="button is-medium" href="{% url 'myapp:status' %}">Check status</a>
        </div>
    </section>
</body>
</html>

myapp/templates/myapp/status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>rishid</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
</head>
<body>
    <section class="hero">
        <div class="hero-body">
        <div class="container">
            <h4 class="title is-4">Hello world!</h4>
            <p class="subtitle">Django, Celery, Redis, Docker example</p>
        </div>
        </div>
    </section>
    <section>
        <div id="app" class="container">
            <p>Task status: ${ current } / ${ total } completed</p>
        </div>
    </section>
    <script>
        var app = new Vue({
            delimiters: ['${', '}'],
            el: "#app",
            data: {
                current: 0,
                total: 0,
                timer: ''
            },
            methods: {
                updateStatus: function() {
                    var self = this;
                    $.getJSON('/get_status/', (info) => {
                        this.current = info["current"];
                        this.total = info["total"];
                        if(this.current == this.total) {
                            clearInterval(this.timer);
                        }
                    });
                }
            },
            created() {
                this.updateStatus();
                this.timer = setInterval(this.updateStatus, 1000)
            },
            beforeDestroy() {
                clearInterval(this.timer);
            }
        })
    </script>
</body>
</html>